/** Shapes returned by the age-estimation API. */

/** `[x, y, w, h]`, integer pixels in the uploaded image's coordinate space. */
export type BBox = [number, number, number, number];

export interface FaceResult {
  bbox: BBox;
  /** Point estimate, years. */
  age: number;
  /** Lower bound of the uncertainty interval (`age - std`), years. */
  low: number;
  /** Upper bound of the uncertainty interval (`age + std`), years. */
  high: number;
  /** 0..1, higher means a tighter predicted distribution. */
  confidence: number;
}

export interface EstimateResponse {
  faces: FaceResult[];
}

/** Per-model user-facing figures, keyed server-side by checkpoint digest.
 *  Null for an artifact we have not measured: no figures and no caveat. */
export interface UserFacing {
  typical_error_years: number;
  typical_error_basis: string;
  gating_under18_shown_adult_pct: number;
  caveat: { min_age: number; short: string; long: string } | null;
}

/** One selectable model, as described by `GET /health`. */
export interface ModelInfo {
  key: string;
  label: string;
  /** What this model predicts, in plain words. The two models answer
   *  different questions; this is the distinction the UI must not blur. */
  question: string;
  explanation: string;
  available: boolean;
  identity_verified: boolean;
  unavailable_reason?: string;
  stub: boolean | null;
  checkpoint: { user_facing?: UserFacing | null } | null;
}

export interface ModelsInfo {
  default: string;
  available: string[];
  models: ModelInfo[];
}

export interface HealthResponse {
  status: string;
  model: string;
  stub: boolean;
  models?: ModelsInfo;
}

/** One model in the static build's `models.json`. */
export interface StaticModelInfo {
  key: string;
  label: string;
  question: string;
  explanation: string;
  available: boolean;
  identity_verified: boolean;
  unavailable_reason?: string;
  /** Filename of the ONNX artifact, relative to the models directory. */
  asset: string | null;
  /** Size of that artifact, used to show a real download percentage. */
  bytes: number | null;
  sha256: string | null;
  checkpoint: {
    user_facing?: UserFacing | null;
    onnx_sha256?: string | null;
    exported_from_sha256?: string | null;
    export_verified?: boolean;
    export_max_logit_diff?: number | null;
    accuracy_note?: string;
  } | null;
}

/**
 * `models.json`: what the static build serves instead of `GET /health`.
 *
 * Generated by `server/tools/export_static_registry.py` from the server's own
 * tables, so the figures cannot be edited here independently of the ones the
 * API reports.
 */
export interface StaticRegistry {
  default: string;
  available: string[];
  models: StaticModelInfo[];
  interval_calibration: {
    nominal: number;
    measured: Record<string, number>;
    corpus: string;
    note: string;
  };
  preprocessing: {
    crop_margin: number;
    input_size: number;
    mean: [number, number, number];
    std: [number, number, number];
    num_bins: number;
    decode: string;
  };
  detector: {
    name: string;
    score_threshold: number;
    nms_threshold: number;
    top_k: number;
    max_detect_side: number;
  };
}
